import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <nav>
        <ul>
          <li>
            <Link href="/">Home</Link>
            <Link href="/order">Order</Link>
          </li>
        </ul>
      </nav>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
